### ISSUE TITLE
[question] How to add this plugin to Remarkable's editor

### ISSUE THREAD

**Issue by SamuelMiller** [jonschlinkert/pretty-remarkable#5]
Hello,
How would I go about getting the pretty-remarkable plugin to work in Remarkable on Linux? I have linuxmint installed. I have gotten as far as "npm install --save pretty-remarkable".  However,  the Remarkable editor does not detect it?

Thanks,
Sam Miller

**Comment by jonschlinkert** [comment]
wrong remarkable. this is for https://github.com/jonschlinkert/remarkable

**Comment by SamuelMiller** [comment]
Thanks.
